server.port = 4545
spring.main.banner-mode=off
logging.level.org.springframework=INFO
#openssl rand -base64 32 =>256-bit key and Safe for HS256
jwt.secretKey = u8RpdDYA+9CM/kuv4pn3Id0PIHpTAGz33tOWZ44DYiE=
# 10 hours
jwt.expiration = 36000000
#-----------------------DB Configurations-------------------------------
spring.datasource.url = jdbc:h2:mem:bookstore
#spring.datasource.url: jdbc:h2:mem:file:D:/h2-db/data
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password = password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto =  update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
#-----------------------H2 DB console configurations----------------------------------------
spring.h2.console.enabled = true
spring.h2.console.path = /h2-console
spring.h2.console.setting.trace = true
spring.h2.console.setting.web-allow-others = true
